import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif, Plus_Jakarta_Sans, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  style: ["normal","italic"],
});

export const metadata: Metadata = {
  title: "ApplyBot – AI-Powered Job Application Automation",
  description:
    "Personalized resumes, cover letters, and perfect job matching – generated by AI. Get hired 10x faster with ApplyBot.",
  keywords:
    "applybot, job applications, resume generator, cover letter ai, job matching, ai career",
  authors: [{ name: "ApplyBot" }],
  openGraph: {
    title: "ApplyBot – Automate Your Job Applications with AI",
    description:
      "Generate tailored resumes and cover letters, and match projects to roles automatically.",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "ApplyBot – AI-Powered Job Applications",
    description: "Automate your applications and get hired faster.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} ${jakarta.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
